// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dto/FightLoadDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FightLoadDTO struct {
	Roomid               int32    `protobuf:"varint,1,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Seat                 int32    `protobuf:"varint,2,opt,name=Seat,proto3" json:"Seat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightLoadDTO) Reset()         { *m = FightLoadDTO{} }
func (m *FightLoadDTO) String() string { return proto.CompactTextString(m) }
func (*FightLoadDTO) ProtoMessage()    {}
func (*FightLoadDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_a01aa1cc82995d03, []int{0}
}

func (m *FightLoadDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightLoadDTO.Unmarshal(m, b)
}
func (m *FightLoadDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightLoadDTO.Marshal(b, m, deterministic)
}
func (m *FightLoadDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightLoadDTO.Merge(m, src)
}
func (m *FightLoadDTO) XXX_Size() int {
	return xxx_messageInfo_FightLoadDTO.Size(m)
}
func (m *FightLoadDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_FightLoadDTO.DiscardUnknown(m)
}

var xxx_messageInfo_FightLoadDTO proto.InternalMessageInfo

func (m *FightLoadDTO) GetRoomid() int32 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *FightLoadDTO) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func init() {
	proto.RegisterType((*FightLoadDTO)(nil), "FightLoadDTO")
}

func init() { proto.RegisterFile("proto/dto/FightLoadDTO.txt", fileDescriptor_a01aa1cc82995d03) }

var fileDescriptor_a01aa1cc82995d03 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x29, 0xc9, 0xd7, 0x77, 0xcb, 0x4c, 0xcf, 0x28, 0xf1, 0xc9, 0x4f, 0x4c, 0x71,
	0x09, 0xf1, 0xd7, 0x2b, 0xa9, 0x28, 0x51, 0xb2, 0xe2, 0xe2, 0x41, 0x16, 0x13, 0x12, 0xe3, 0x62,
	0x0b, 0xca, 0xcf, 0xcf, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf2, 0x84,
	0x84, 0xb8, 0x58, 0x82, 0x53, 0x13, 0x4b, 0x24, 0x98, 0xc0, 0xa2, 0x60, 0x76, 0x12, 0x1b, 0xd8,
	0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x27, 0x41, 0xa3, 0x60, 0x00, 0x00, 0x00,
}
