// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LoginTypes.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginTypes int32

const (
	LoginTypes_LOGIN_CREQ LoginTypes = 0
	LoginTypes_LOGIN_SRES LoginTypes = 1
	LoginTypes_REG_CREQ   LoginTypes = 2
	LoginTypes_REG_SRES   LoginTypes = 3
)

var LoginTypes_name = map[int32]string{
	0: "LOGIN_CREQ",
	1: "LOGIN_SRES",
	2: "REG_CREQ",
	3: "REG_SRES",
}

var LoginTypes_value = map[string]int32{
	"LOGIN_CREQ": 0,
	"LOGIN_SRES": 1,
	"REG_CREQ":   2,
	"REG_SRES":   3,
}

func (x LoginTypes) String() string {
	return proto.EnumName(LoginTypes_name, int32(x))
}

func (LoginTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_74f522b34ed12c35, []int{0}
}

func init() {
	proto.RegisterEnum("LoginTypes", LoginTypes_name, LoginTypes_value)
}

func init() { proto.RegisterFile("LoginTypes.txt", fileDescriptor_74f522b34ed12c35) }

var fileDescriptor_74f522b34ed12c35 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf3, 0xc9, 0x4f, 0xcf,
	0xcc, 0x0b, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0xa9, 0x28, 0xd1, 0xf2, 0xe0, 0xe2, 0x42, 0x88,
	0x08, 0xf1, 0x71, 0x71, 0xf9, 0xf8, 0xbb, 0x7b, 0xfa, 0xc5, 0x3b, 0x07, 0xb9, 0x06, 0x0a, 0x30,
	0x20, 0xf8, 0xc1, 0x41, 0xae, 0xc1, 0x02, 0x8c, 0x42, 0x3c, 0x5c, 0x1c, 0x41, 0xae, 0xee, 0x10,
	0x59, 0x26, 0x18, 0x0f, 0x2c, 0xc7, 0x9c, 0xc4, 0x56, 0x50, 0x94, 0x5f, 0x92, 0x6f, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x6f, 0x5c, 0x72, 0x62, 0x00, 0x00, 0x00,
}
