// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MatchSuccessDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchSuccessDTO struct {
	Roomid               int32     `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	X                    float32   `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Z                    float32   `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Speed                float32   `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Count                int32     `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Players              []*Player `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MatchSuccessDTO) Reset()         { *m = MatchSuccessDTO{} }
func (m *MatchSuccessDTO) String() string { return proto.CompactTextString(m) }
func (*MatchSuccessDTO) ProtoMessage()    {}
func (*MatchSuccessDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_b675b7cb50823ddd, []int{0}
}

func (m *MatchSuccessDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchSuccessDTO.Unmarshal(m, b)
}
func (m *MatchSuccessDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchSuccessDTO.Marshal(b, m, deterministic)
}
func (m *MatchSuccessDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchSuccessDTO.Merge(m, src)
}
func (m *MatchSuccessDTO) XXX_Size() int {
	return xxx_messageInfo_MatchSuccessDTO.Size(m)
}
func (m *MatchSuccessDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchSuccessDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MatchSuccessDTO proto.InternalMessageInfo

func (m *MatchSuccessDTO) GetRoomid() int32 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *MatchSuccessDTO) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MatchSuccessDTO) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *MatchSuccessDTO) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *MatchSuccessDTO) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MatchSuccessDTO) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Player struct {
	Playerid             int32    `protobuf:"varint,1,opt,name=playerid,proto3" json:"playerid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Roleid               int32    `protobuf:"varint,3,opt,name=roleid,proto3" json:"roleid,omitempty"`
	Seat                 int32    `protobuf:"varint,4,opt,name=seat,proto3" json:"seat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_b675b7cb50823ddd, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerid() int32 {
	if m != nil {
		return m.Playerid
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetRoleid() int32 {
	if m != nil {
		return m.Roleid
	}
	return 0
}

func (m *Player) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func init() {
	proto.RegisterType((*MatchSuccessDTO)(nil), "MatchSuccessDTO")
	proto.RegisterType((*Player)(nil), "Player")
}

func init() { proto.RegisterFile("MatchSuccessDTO.txt", fileDescriptor_b675b7cb50823ddd) }

var fileDescriptor_b675b7cb50823ddd = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x41, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0x49, 0xdb, 0xa4, 0xfa, 0x14, 0x84, 0x28, 0x12, 0x5c, 0xd5, 0xae, 0xba, 0xea, 0x42,
	0xaf, 0xe0, 0x56, 0x94, 0xe8, 0x05, 0x62, 0x12, 0xb0, 0xd0, 0x36, 0xa5, 0x49, 0xa1, 0xd3, 0x73,
	0xcc, 0x81, 0x87, 0xbc, 0xcc, 0x74, 0x31, 0xbb, 0xff, 0xfb, 0x78, 0x3c, 0x3e, 0x78, 0xfc, 0x54,
	0x41, 0xff, 0xff, 0x2c, 0x5a, 0x5b, 0xef, 0x3f, 0x7e, 0xbf, 0xda, 0xb0, 0x86, 0xfa, 0x48, 0xe0,
	0xe1, 0xca, 0xf3, 0x67, 0x60, 0xb3, 0x73, 0x43, 0x67, 0x04, 0xa9, 0x48, 0x43, 0xe5, 0x99, 0xf8,
	0x3d, 0x90, 0x55, 0x64, 0x15, 0x69, 0x32, 0x49, 0xd6, 0x48, 0x9b, 0xc8, 0x13, 0x6d, 0xfc, 0x09,
	0xa8, 0x9f, 0xac, 0x35, 0xa2, 0x40, 0x93, 0x20, 0x5a, 0xed, 0x96, 0x31, 0x08, 0x8a, 0x8f, 0x12,
	0xf0, 0x57, 0x28, 0xa7, 0x5e, 0x1d, 0xec, 0xec, 0x05, 0xab, 0xf2, 0xe6, 0xee, 0xad, 0x6c, 0xbf,
	0x91, 0xe5, 0xc5, 0xd7, 0x06, 0x58, 0x52, 0xfc, 0x05, 0x6e, 0x92, 0xdc, 0x73, 0x76, 0xe6, 0x1c,
	0x8a, 0x51, 0x0d, 0x16, 0x9b, 0x6e, 0x25, 0xee, 0x14, 0xdf, 0xdb, 0xce, 0x60, 0x1b, 0xc6, 0x47,
	0x8a, 0xb7, 0xde, 0xaa, 0x80, 0x7d, 0x54, 0xe2, 0xfe, 0x63, 0xd3, 0xec, 0x82, 0x7b, 0x3f, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xb5, 0x80, 0x30, 0x91, 0x1a, 0x01, 0x00, 0x00,
}
