// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dto/MatchRtnDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchRtnDTO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cacheroomid          int32    `protobuf:"varint,2,opt,name=Cacheroomid,proto3" json:"Cacheroomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchRtnDTO) Reset()         { *m = MatchRtnDTO{} }
func (m *MatchRtnDTO) String() string { return proto.CompactTextString(m) }
func (*MatchRtnDTO) ProtoMessage()    {}
func (*MatchRtnDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_0390a2be43e52911, []int{0}
}

func (m *MatchRtnDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchRtnDTO.Unmarshal(m, b)
}
func (m *MatchRtnDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchRtnDTO.Marshal(b, m, deterministic)
}
func (m *MatchRtnDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchRtnDTO.Merge(m, src)
}
func (m *MatchRtnDTO) XXX_Size() int {
	return xxx_messageInfo_MatchRtnDTO.Size(m)
}
func (m *MatchRtnDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchRtnDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MatchRtnDTO proto.InternalMessageInfo

func (m *MatchRtnDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatchRtnDTO) GetCacheroomid() int32 {
	if m != nil {
		return m.Cacheroomid
	}
	return 0
}

func init() {
	proto.RegisterType((*MatchRtnDTO)(nil), "MatchRtnDTO")
}

func init() { proto.RegisterFile("proto/dto/MatchRtnDTO.txt", fileDescriptor_0390a2be43e52911) }

var fileDescriptor_0390a2be43e52911 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x29, 0xc9, 0xd7, 0xf7, 0x4d, 0x2c, 0x49, 0xce, 0x08, 0x2a, 0xc9, 0x73, 0x09,
	0xf1, 0xd7, 0x2b, 0xa9, 0x28, 0x51, 0xb2, 0xe7, 0xe2, 0x46, 0x12, 0x12, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x52, 0xe0, 0xe2, 0x76,
	0x4e, 0x4c, 0xce, 0x48, 0x2d, 0xca, 0xcf, 0xcf, 0xcd, 0x4c, 0x91, 0x60, 0x02, 0x4b, 0x20, 0x0b,
	0x25, 0xb1, 0x81, 0xcd, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x90, 0xcc, 0xc6, 0xc6, 0x64,
	0x00, 0x00, 0x00,
}
