// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MatchDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchDTO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoleID               int32    `protobuf:"varint,3,opt,name=roleID,proto3" json:"roleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchDTO) Reset()         { *m = MatchDTO{} }
func (m *MatchDTO) String() string { return proto.CompactTextString(m) }
func (*MatchDTO) ProtoMessage()    {}
func (*MatchDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_a262405ee8f86aca, []int{0}
}

func (m *MatchDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchDTO.Unmarshal(m, b)
}
func (m *MatchDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchDTO.Marshal(b, m, deterministic)
}
func (m *MatchDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchDTO.Merge(m, src)
}
func (m *MatchDTO) XXX_Size() int {
	return xxx_messageInfo_MatchDTO.Size(m)
}
func (m *MatchDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MatchDTO proto.InternalMessageInfo

func (m *MatchDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatchDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MatchDTO) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func init() {
	proto.RegisterType((*MatchDTO)(nil), "MatchDTO")
}

func init() { proto.RegisterFile("MatchDTO.txt", fileDescriptor_a262405ee8f86aca) }

var fileDescriptor_a262405ee8f86aca = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf1, 0x4d, 0x2c, 0x49,
	0xce, 0x70, 0x09, 0xf1, 0xd7, 0x2b, 0xa9, 0x28, 0x51, 0x72, 0xe3, 0xe2, 0x80, 0xf1, 0x85, 0xf8,
	0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21,
	0x31, 0x2e, 0xb6, 0xa2, 0xfc, 0x9c, 0x54, 0x4f, 0x17, 0x09, 0x66, 0xb0, 0x3a, 0x28, 0x2f, 0x89,
	0xad, 0xa0, 0x28, 0xbf, 0x24, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x78, 0x12, 0x17,
	0x5e, 0x00, 0x00, 0x00,
}
