// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MatchTypes.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchTypes int32

const (
	MatchTypes_ENTER_CREQ       MatchTypes = 0
	MatchTypes_ENTER_SRES       MatchTypes = 1
	MatchTypes_LEAVE_CREQ       MatchTypes = 2
	MatchTypes_LEAVE_SRES       MatchTypes = 3
	MatchTypes_ENTER_SELECT_BRO MatchTypes = 4
)

var MatchTypes_name = map[int32]string{
	0: "ENTER_CREQ",
	1: "ENTER_SRES",
	2: "LEAVE_CREQ",
	3: "LEAVE_SRES",
	4: "ENTER_SELECT_BRO",
}

var MatchTypes_value = map[string]int32{
	"ENTER_CREQ":       0,
	"ENTER_SRES":       1,
	"LEAVE_CREQ":       2,
	"LEAVE_SRES":       3,
	"ENTER_SELECT_BRO": 4,
}

func (x MatchTypes) String() string {
	return proto.EnumName(MatchTypes_name, int32(x))
}

func (MatchTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9574753d10f9d38, []int{0}
}

func init() {
	proto.RegisterEnum("MatchTypes", MatchTypes_name, MatchTypes_value)
}

func init() { proto.RegisterFile("MatchTypes.txt", fileDescriptor_f9574753d10f9d38) }

var fileDescriptor_f9574753d10f9d38 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf3, 0x4d, 0x2c, 0x49,
	0xce, 0x08, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0xa9, 0x28, 0xd1, 0x4a, 0xe2, 0xe2, 0x42, 0x88,
	0x08, 0xf1, 0x71, 0x71, 0xb9, 0xfa, 0x85, 0xb8, 0x06, 0xc5, 0x3b, 0x07, 0xb9, 0x06, 0x0a, 0x30,
	0x20, 0xf8, 0xc1, 0x41, 0xae, 0xc1, 0x02, 0x8c, 0x20, 0xbe, 0x8f, 0xab, 0x63, 0x98, 0x2b, 0x44,
	0x9e, 0x09, 0xc1, 0x07, 0xcb, 0x33, 0x0b, 0x89, 0x70, 0x09, 0x40, 0xd5, 0xbb, 0xfa, 0xb8, 0x3a,
	0x87, 0xc4, 0x3b, 0x05, 0xf9, 0x0b, 0xb0, 0x24, 0xb1, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xee, 0x35, 0x01, 0x7c, 0x00, 0x00, 0x00,
}
