// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dto/MatchSuccessDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchSuccessDTO struct {
	Roomid               int32        `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Count                int32        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Speed                float32      `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Players              []*PlayerDTO `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	Lights               []*LightDTO  `protobuf:"bytes,5,rep,name=lights,proto3" json:"lights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MatchSuccessDTO) Reset()         { *m = MatchSuccessDTO{} }
func (m *MatchSuccessDTO) String() string { return proto.CompactTextString(m) }
func (*MatchSuccessDTO) ProtoMessage()    {}
func (*MatchSuccessDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_461d439e328d2266, []int{0}
}

func (m *MatchSuccessDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchSuccessDTO.Unmarshal(m, b)
}
func (m *MatchSuccessDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchSuccessDTO.Marshal(b, m, deterministic)
}
func (m *MatchSuccessDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchSuccessDTO.Merge(m, src)
}
func (m *MatchSuccessDTO) XXX_Size() int {
	return xxx_messageInfo_MatchSuccessDTO.Size(m)
}
func (m *MatchSuccessDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchSuccessDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MatchSuccessDTO proto.InternalMessageInfo

func (m *MatchSuccessDTO) GetRoomid() int32 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *MatchSuccessDTO) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MatchSuccessDTO) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *MatchSuccessDTO) GetPlayers() []*PlayerDTO {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *MatchSuccessDTO) GetLights() []*LightDTO {
	if m != nil {
		return m.Lights
	}
	return nil
}

type PlayerDTO struct {
	Playerid             int32    `protobuf:"varint,1,opt,name=playerid,proto3" json:"playerid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Roleid               int32    `protobuf:"varint,3,opt,name=roleid,proto3" json:"roleid,omitempty"`
	Seat                 int32    `protobuf:"varint,4,opt,name=seat,proto3" json:"seat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDTO) Reset()         { *m = PlayerDTO{} }
func (m *PlayerDTO) String() string { return proto.CompactTextString(m) }
func (*PlayerDTO) ProtoMessage()    {}
func (*PlayerDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_461d439e328d2266, []int{1}
}

func (m *PlayerDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDTO.Unmarshal(m, b)
}
func (m *PlayerDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDTO.Marshal(b, m, deterministic)
}
func (m *PlayerDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDTO.Merge(m, src)
}
func (m *PlayerDTO) XXX_Size() int {
	return xxx_messageInfo_PlayerDTO.Size(m)
}
func (m *PlayerDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDTO.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDTO proto.InternalMessageInfo

func (m *PlayerDTO) GetPlayerid() int32 {
	if m != nil {
		return m.Playerid
	}
	return 0
}

func (m *PlayerDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerDTO) GetRoleid() int32 {
	if m != nil {
		return m.Roleid
	}
	return 0
}

func (m *PlayerDTO) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

type LightDTO struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z                    float32  `protobuf:"fixed32,2,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LightDTO) Reset()         { *m = LightDTO{} }
func (m *LightDTO) String() string { return proto.CompactTextString(m) }
func (*LightDTO) ProtoMessage()    {}
func (*LightDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_461d439e328d2266, []int{2}
}

func (m *LightDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightDTO.Unmarshal(m, b)
}
func (m *LightDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightDTO.Marshal(b, m, deterministic)
}
func (m *LightDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightDTO.Merge(m, src)
}
func (m *LightDTO) XXX_Size() int {
	return xxx_messageInfo_LightDTO.Size(m)
}
func (m *LightDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_LightDTO.DiscardUnknown(m)
}

var xxx_messageInfo_LightDTO proto.InternalMessageInfo

func (m *LightDTO) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *LightDTO) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*MatchSuccessDTO)(nil), "MatchSuccessDTO")
	proto.RegisterType((*PlayerDTO)(nil), "PlayerDTO")
	proto.RegisterType((*LightDTO)(nil), "LightDTO")
}

func init() { proto.RegisterFile("proto/dto/MatchSuccessDTO.txt", fileDescriptor_461d439e328d2266) }

var fileDescriptor_461d439e328d2266 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x51, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x34, 0x89, 0xcd, 0x28, 0x08, 0x83, 0xc8, 0x22, 0x08, 0x31, 0x88, 0xe4, 0x29,
	0x05, 0xbd, 0x42, 0x1f, 0x95, 0xca, 0xda, 0x0b, 0xc4, 0xcd, 0xd2, 0x06, 0xd2, 0x6e, 0xc8, 0x4e,
	0x21, 0xf6, 0x30, 0x9e, 0x55, 0x76, 0xb6, 0xc9, 0x83, 0x6f, 0xf3, 0xfd, 0xf3, 0xcf, 0xce, 0x3f,
	0x0b, 0x8f, 0xfd, 0x60, 0xc9, 0xae, 0x1a, 0xb2, 0xab, 0x8f, 0x9a, 0xf4, 0xfe, 0xeb, 0xa4, 0xb5,
	0x71, 0x6e, 0xbd, 0xdd, 0x54, 0x34, 0x52, 0xf1, 0x2b, 0xe0, 0xf6, 0x9f, 0x8e, 0xf7, 0x90, 0x0e,
	0xd6, 0x1e, 0xda, 0x46, 0x8a, 0x5c, 0x94, 0x89, 0xba, 0x10, 0xde, 0x41, 0xa2, 0xed, 0xe9, 0x48,
	0x32, 0x62, 0x39, 0x80, 0x57, 0x5d, 0x6f, 0x4c, 0x23, 0x17, 0xb9, 0x28, 0x23, 0x15, 0x00, 0x9f,
	0xe1, 0xaa, 0xef, 0xea, 0x1f, 0x33, 0x38, 0x19, 0xe7, 0x8b, 0xf2, 0xfa, 0x15, 0xaa, 0x4f, 0xe6,
	0xf5, 0x76, 0xa3, 0xa6, 0x16, 0x3e, 0x41, 0xda, 0xb5, 0xbb, 0x3d, 0x39, 0x99, 0xb0, 0x29, 0xab,
	0xde, 0x3d, 0x7a, 0xcf, 0xa5, 0x51, 0xec, 0x20, 0x9b, 0x07, 0xf1, 0x01, 0x96, 0x61, 0x74, 0xce,
	0x36, 0x33, 0x22, 0xc4, 0xc7, 0xfa, 0x60, 0x38, 0x5c, 0xa6, 0xb8, 0x0e, 0x97, 0x74, 0xa6, 0x0d,
	0xe1, 0xf8, 0x12, 0x4f, 0xde, 0xeb, 0x4c, 0x4d, 0x32, 0x66, 0x95, 0xeb, 0xe2, 0x05, 0x96, 0xd3,
	0x72, 0xbc, 0x01, 0x31, 0xf2, 0x82, 0x48, 0x89, 0xd1, 0xd3, 0x99, 0x9f, 0x8d, 0x94, 0x38, 0x7f,
	0xa7, 0xfc, 0xa1, 0x6f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xd6, 0x60, 0x18, 0x59, 0x01,
	0x00, 0x00,
}
