// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dto/MoveDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Direction struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Direction) Reset()         { *m = Direction{} }
func (m *Direction) String() string { return proto.CompactTextString(m) }
func (*Direction) ProtoMessage()    {}
func (*Direction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5494fd5bbe534eec, []int{0}
}

func (m *Direction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Direction.Unmarshal(m, b)
}
func (m *Direction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Direction.Marshal(b, m, deterministic)
}
func (m *Direction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Direction.Merge(m, src)
}
func (m *Direction) XXX_Size() int {
	return xxx_messageInfo_Direction.Size(m)
}
func (m *Direction) XXX_DiscardUnknown() {
	xxx_messageInfo_Direction.DiscardUnknown(m)
}

var xxx_messageInfo_Direction proto.InternalMessageInfo

func (m *Direction) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Direction) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type FrameInfo struct {
	Frame                int32      `protobuf:"varint,1,opt,name=Frame,proto3" json:"Frame,omitempty"`
	Move                 *Direction `protobuf:"bytes,2,opt,name=Move,proto3" json:"Move,omitempty"`
	Skillid              int32      `protobuf:"varint,3,opt,name=Skillid,proto3" json:"Skillid,omitempty"`
	SkillDir             *Direction `protobuf:"bytes,4,opt,name=SkillDir,proto3" json:"SkillDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FrameInfo) Reset()         { *m = FrameInfo{} }
func (m *FrameInfo) String() string { return proto.CompactTextString(m) }
func (*FrameInfo) ProtoMessage()    {}
func (*FrameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5494fd5bbe534eec, []int{1}
}

func (m *FrameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameInfo.Unmarshal(m, b)
}
func (m *FrameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameInfo.Marshal(b, m, deterministic)
}
func (m *FrameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameInfo.Merge(m, src)
}
func (m *FrameInfo) XXX_Size() int {
	return xxx_messageInfo_FrameInfo.Size(m)
}
func (m *FrameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FrameInfo proto.InternalMessageInfo

func (m *FrameInfo) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *FrameInfo) GetMove() *Direction {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *FrameInfo) GetSkillid() int32 {
	if m != nil {
		return m.Skillid
	}
	return 0
}

func (m *FrameInfo) GetSkillDir() *Direction {
	if m != nil {
		return m.SkillDir
	}
	return nil
}

type ClientMoveDTO struct {
	Roomid               int32        `protobuf:"varint,1,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Seat                 int32        `protobuf:"varint,2,opt,name=Seat,proto3" json:"Seat,omitempty"`
	Bagid                int32        `protobuf:"varint,3,opt,name=Bagid,proto3" json:"Bagid,omitempty"`
	Msg                  []*FrameInfo `protobuf:"bytes,4,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClientMoveDTO) Reset()         { *m = ClientMoveDTO{} }
func (m *ClientMoveDTO) String() string { return proto.CompactTextString(m) }
func (*ClientMoveDTO) ProtoMessage()    {}
func (*ClientMoveDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_5494fd5bbe534eec, []int{2}
}

func (m *ClientMoveDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMoveDTO.Unmarshal(m, b)
}
func (m *ClientMoveDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMoveDTO.Marshal(b, m, deterministic)
}
func (m *ClientMoveDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMoveDTO.Merge(m, src)
}
func (m *ClientMoveDTO) XXX_Size() int {
	return xxx_messageInfo_ClientMoveDTO.Size(m)
}
func (m *ClientMoveDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMoveDTO.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMoveDTO proto.InternalMessageInfo

func (m *ClientMoveDTO) GetRoomid() int32 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *ClientMoveDTO) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *ClientMoveDTO) GetBagid() int32 {
	if m != nil {
		return m.Bagid
	}
	return 0
}

func (m *ClientMoveDTO) GetMsg() []*FrameInfo {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ClientDTO struct {
	Seat                 int32        `protobuf:"varint,1,opt,name=Seat,proto3" json:"Seat,omitempty"`
	Msg                  []*FrameInfo `protobuf:"bytes,2,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClientDTO) Reset()         { *m = ClientDTO{} }
func (m *ClientDTO) String() string { return proto.CompactTextString(m) }
func (*ClientDTO) ProtoMessage()    {}
func (*ClientDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_5494fd5bbe534eec, []int{3}
}

func (m *ClientDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDTO.Unmarshal(m, b)
}
func (m *ClientDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDTO.Marshal(b, m, deterministic)
}
func (m *ClientDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDTO.Merge(m, src)
}
func (m *ClientDTO) XXX_Size() int {
	return xxx_messageInfo_ClientDTO.Size(m)
}
func (m *ClientDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDTO.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDTO proto.InternalMessageInfo

func (m *ClientDTO) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *ClientDTO) GetMsg() []*FrameInfo {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ServerMoveDTO struct {
	Bagid                int32        `protobuf:"varint,1,opt,name=Bagid,proto3" json:"Bagid,omitempty"`
	ClientInfo           []*ClientDTO `protobuf:"bytes,2,rep,name=clientInfo,proto3" json:"clientInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServerMoveDTO) Reset()         { *m = ServerMoveDTO{} }
func (m *ServerMoveDTO) String() string { return proto.CompactTextString(m) }
func (*ServerMoveDTO) ProtoMessage()    {}
func (*ServerMoveDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_5494fd5bbe534eec, []int{4}
}

func (m *ServerMoveDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMoveDTO.Unmarshal(m, b)
}
func (m *ServerMoveDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMoveDTO.Marshal(b, m, deterministic)
}
func (m *ServerMoveDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMoveDTO.Merge(m, src)
}
func (m *ServerMoveDTO) XXX_Size() int {
	return xxx_messageInfo_ServerMoveDTO.Size(m)
}
func (m *ServerMoveDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMoveDTO.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMoveDTO proto.InternalMessageInfo

func (m *ServerMoveDTO) GetBagid() int32 {
	if m != nil {
		return m.Bagid
	}
	return 0
}

func (m *ServerMoveDTO) GetClientInfo() []*ClientDTO {
	if m != nil {
		return m.ClientInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Direction)(nil), "Direction")
	proto.RegisterType((*FrameInfo)(nil), "FrameInfo")
	proto.RegisterType((*ClientMoveDTO)(nil), "ClientMoveDTO")
	proto.RegisterType((*ClientDTO)(nil), "ClientDTO")
	proto.RegisterType((*ServerMoveDTO)(nil), "ServerMoveDTO")
}

func init() { proto.RegisterFile("proto/dto/MoveDTO.txt", fileDescriptor_5494fd5bbe534eec) }

var fileDescriptor_5494fd5bbe534eec = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x49, 0x3f, 0x56, 0x3b, 0xba, 0x97, 0xa0, 0x92, 0x83, 0xc8, 0xd2, 0x83, 0x8a, 0x87,
	0x5d, 0xd0, 0xb3, 0x17, 0x2d, 0x82, 0x07, 0x11, 0x53, 0x5f, 0xa0, 0x6e, 0xe3, 0x12, 0x6c, 0x3b,
	0x12, 0xc3, 0xd2, 0x3d, 0xfb, 0xe2, 0x92, 0x69, 0x1a, 0x0a, 0xee, 0x2d, 0xbf, 0x99, 0xfe, 0x3f,
	0x86, 0xc2, 0xe9, 0xb7, 0x41, 0x8b, 0xab, 0xda, 0xe2, 0xea, 0x05, 0xb7, 0xaa, 0x78, 0x7f, 0x5d,
	0xda, 0xde, 0xe6, 0x57, 0x90, 0x15, 0xda, 0xa8, 0xb5, 0xd5, 0xd8, 0xf1, 0x63, 0x60, 0xbd, 0x60,
	0x0b, 0x76, 0x1d, 0x49, 0xd6, 0x3b, 0xda, 0x89, 0x68, 0xa0, 0x5d, 0xfe, 0xcb, 0x20, 0x7b, 0x32,
	0x55, 0xab, 0x9e, 0xbb, 0x4f, 0xe4, 0x27, 0x90, 0x12, 0xd0, 0xd7, 0xa9, 0x1c, 0x80, 0x5f, 0x40,
	0xe2, 0xbc, 0x49, 0x74, 0x74, 0x0b, 0xcb, 0xe0, 0x2c, 0x69, 0xce, 0x05, 0x1c, 0x94, 0x5f, 0xba,
	0x69, 0x74, 0x2d, 0x62, 0xd2, 0x8d, 0xc8, 0x2f, 0xe1, 0x90, 0x9e, 0x85, 0x36, 0x22, 0xf9, 0xa7,
	0x0e, 0xbb, 0x1c, 0x61, 0xfe, 0xd8, 0x68, 0xd5, 0x59, 0x7f, 0x03, 0x3f, 0x83, 0x99, 0x44, 0x6c,
	0x75, 0xed, 0x9b, 0x78, 0xe2, 0x1c, 0x92, 0x52, 0x55, 0x96, 0xaa, 0xa4, 0x92, 0xde, 0xae, 0xf4,
	0x43, 0xb5, 0x09, 0xe1, 0x03, 0xf0, 0x73, 0x88, 0xdb, 0x9f, 0x8d, 0x48, 0x16, 0x31, 0xa5, 0x86,
	0x1b, 0xa5, 0x1b, 0xe7, 0xf7, 0x90, 0x0d, 0x81, 0x2e, 0x6c, 0x34, 0x65, 0x13, 0x53, 0x2f, 0x8f,
	0xf6, 0xcb, 0xdf, 0x60, 0x5e, 0x2a, 0xb3, 0x55, 0x66, 0xec, 0x1b, 0x3a, 0xb0, 0x69, 0x87, 0x1b,
	0x80, 0x35, 0xa5, 0x38, 0x65, 0xf0, 0x0a, 0xc1, 0x72, 0xb2, 0xfd, 0x98, 0xd1, 0x8f, 0xbc, 0xfb,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xd2, 0xda, 0x3c, 0xd1, 0x01, 0x00, 0x00,
}
