// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MoveDTO.txt

package DTO

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MoveDTO struct {
	Roomid               int32    `protobuf:"varint,1,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Seat                 int32    `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	DeltaTime            float32  `protobuf:"fixed32,5,opt,name=deltaTime,proto3" json:"deltaTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDTO) Reset()         { *m = MoveDTO{} }
func (m *MoveDTO) String() string { return proto.CompactTextString(m) }
func (*MoveDTO) ProtoMessage()    {}
func (*MoveDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2000b3ef7a9ea64, []int{0}
}

func (m *MoveDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDTO.Unmarshal(m, b)
}
func (m *MoveDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDTO.Marshal(b, m, deterministic)
}
func (m *MoveDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDTO.Merge(m, src)
}
func (m *MoveDTO) XXX_Size() int {
	return xxx_messageInfo_MoveDTO.Size(m)
}
func (m *MoveDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDTO proto.InternalMessageInfo

func (m *MoveDTO) GetRoomid() int32 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *MoveDTO) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *MoveDTO) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveDTO) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MoveDTO) GetDeltaTime() float32 {
	if m != nil {
		return m.DeltaTime
	}
	return 0
}

func init() {
	proto.RegisterType((*MoveDTO)(nil), "MoveDTO")
}

func init() { proto.RegisterFile("MoveDTO.txt", fileDescriptor_e2000b3ef7a9ea64) }

var fileDescriptor_e2000b3ef7a9ea64 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf6, 0xcd, 0x2f, 0x4b,
	0x75, 0x09, 0xf1, 0xd7, 0x2b, 0xa9, 0x28, 0x51, 0xca, 0xe7, 0x62, 0x87, 0x72, 0x85, 0xc4, 0xb8,
	0xd8, 0x82, 0xf2, 0xf3, 0x73, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c,
	0x21, 0x21, 0x2e, 0x96, 0xe2, 0xd4, 0xc4, 0x12, 0x09, 0x26, 0xb0, 0x28, 0x98, 0x2d, 0xc4, 0xc3,
	0xc5, 0x58, 0x21, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x14, 0xc4, 0x58, 0x01, 0xe2, 0x55, 0x4a, 0xb0,
	0x40, 0x78, 0x95, 0x42, 0x32, 0x5c, 0x9c, 0x29, 0xa9, 0x39, 0x25, 0x89, 0x21, 0x99, 0xb9, 0xa9,
	0x12, 0xac, 0x60, 0x51, 0x84, 0x40, 0x12, 0x5b, 0x41, 0x51, 0x7e, 0x49, 0xbe, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x19, 0xf1, 0xd0, 0x86, 0x00, 0x00, 0x00,
}
