// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/dto/FightLeaveDTO.txt
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/dto/FightLeaveDTO.txt</summary>
public static partial class FightLeaveDTOReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/dto/FightLeaveDTO.txt</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FightLeaveDTOReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chtwcm90by9kdG8vRmlnaHRMZWF2ZURUTy50eHQiLQoNRmlnaHRMZWF2ZURU",
          "TxIOCgZSb29taWQYASABKAUSDAoEU2VhdBgCIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::FightLeaveDTO), global::FightLeaveDTO.Parser, new[]{ "Roomid", "Seat" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class FightLeaveDTO : pb::IMessage<FightLeaveDTO> {
  private static readonly pb::MessageParser<FightLeaveDTO> _parser = new pb::MessageParser<FightLeaveDTO>(() => new FightLeaveDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FightLeaveDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FightLeaveDTOReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FightLeaveDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FightLeaveDTO(FightLeaveDTO other) : this() {
    roomid_ = other.roomid_;
    seat_ = other.seat_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FightLeaveDTO Clone() {
    return new FightLeaveDTO(this);
  }

  /// <summary>Field number for the "Roomid" field.</summary>
  public const int RoomidFieldNumber = 1;
  private int roomid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Roomid {
    get { return roomid_; }
    set {
      roomid_ = value;
    }
  }

  /// <summary>Field number for the "Seat" field.</summary>
  public const int SeatFieldNumber = 2;
  private int seat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Seat {
    get { return seat_; }
    set {
      seat_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FightLeaveDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FightLeaveDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Roomid != other.Roomid) return false;
    if (Seat != other.Seat) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Roomid != 0) hash ^= Roomid.GetHashCode();
    if (Seat != 0) hash ^= Seat.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Roomid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Roomid);
    }
    if (Seat != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Seat);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Roomid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Roomid);
    }
    if (Seat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seat);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FightLeaveDTO other) {
    if (other == null) {
      return;
    }
    if (other.Roomid != 0) {
      Roomid = other.Roomid;
    }
    if (other.Seat != 0) {
      Seat = other.Seat;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Roomid = input.ReadInt32();
          break;
        }
        case 16: {
          Seat = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
