// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/FightTypes.txt
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/FightTypes.txt</summary>
public static partial class FightTypesReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/FightTypes.txt</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FightTypesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRwcm90by9GaWdodFR5cGVzLnR4dCq4AQoKRmlnaHRUeXBlcxINCglNT1ZF",
          "X0NSRVEQABIPCgtJTkZPUk1fU1JFUxABEhAKDExPQURfVVBfQ1JFURACEhAK",
          "DExPQURfVVBfU1JFUxADEg4KCkRFQVRIX0NSRVEQBBIOCgpERUFUSF9TUkVT",
          "EAUSEgoOR0FNRV9PVkVSX0NSRVEQBhISCg5HQU1FX09WRVJfU1JFUxAHEg4K",
          "CkxBRVZFX0NSRVEQCBIOCgpMQUVWRV9TUkVTEAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FightTypes), }, null, null));
  }
  #endregion

}
#region Enums
public enum FightTypes {
  [pbr::OriginalName("MOVE_CREQ")] MoveCreq = 0,
  [pbr::OriginalName("INFORM_SRES")] InformSres = 1,
  [pbr::OriginalName("LOAD_UP_CREQ")] LoadUpCreq = 2,
  [pbr::OriginalName("LOAD_UP_SRES")] LoadUpSres = 3,
  [pbr::OriginalName("DEATH_CREQ")] DeathCreq = 4,
  [pbr::OriginalName("DEATH_SRES")] DeathSres = 5,
  [pbr::OriginalName("GAME_OVER_CREQ")] GameOverCreq = 6,
  [pbr::OriginalName("GAME_OVER_SRES")] GameOverSres = 7,
  [pbr::OriginalName("LAEVE_CREQ")] LaeveCreq = 8,
  [pbr::OriginalName("LAEVE_SRES")] LaeveSres = 9,
}

#endregion


#endregion Designer generated code
